Hospital/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('booking/', views.booking, name='booking'), 
    path('doctors/', views.Doctor, name='Doctor'),
    path('departments/', views.Department, name='Department'),
    path('booking_success/', views.booking_success, name='booking_success'),
    
    
    
]

home/models.py
from django.db import models

# Create your models here.

class Departments(models.Model):
    dep_name = models.CharField(max_length=50)
    dep_description = models.TextField()
    def __str__(self):
        return self.dep_name

class Doctors(models.Model):
    doc_name = models.CharField(max_length=255)
    doc_spec = models.CharField(max_length=255)
    dep_name = models.ForeignKey(Departments, on_delete=models.CASCADE)
    doc_image = models.ImageField(upload_to='doctors')
    def __str__(self):
        return f"Dr. {self.doc_name} - {self.doc_spec}"

class Booking(models.Model):
    
    patient_name = models.CharField(max_length=100)
    patient_email = models.EmailField()
    patient_phone =models.CharField(max_length=15)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('TM', 'Trans Men'),
        ('TW', 'Trans Women'),
        ('O', 'Other'),
    ]
    patient_gender = models.CharField(max_length=2, choices=GENDER_CHOICES,default='')
    AGE_CHOICES = [(i, str(i)) for i in range(0, 151)]
    patient_age = models.IntegerField(choices=AGE_CHOICES, default=0)
    doctor = models.ForeignKey(Doctors, on_delete=models.CASCADE)
    PATIENT_CHOICES = [
    ('Normal Patient- I can visit the hospital', 'Normal Patient- I can visit the hospital'),
    ('Bedridden Patient', 'Bedridden Patient'),
    ('Pregnant Lady', 'Pregnant Lady'),
    ('Other - I can not visit the Hospital', 'Other - I can not visit the Hospital'),
    ('Need Online consultancy', 'Need Online consultancy'),
    ]
    patient_type = models.CharField(max_length=50, choices=PATIENT_CHOICES, default='select patient type')

    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    booked_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.patient_name

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name
       
       
class Prescription(models.Model):
    patient_name = models.ForeignKey(Booking, on_delete=models.CASCADE)
    doctor_name = models.ForeignKey(Doctors, on_delete=models.CASCADE)
    medication = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.medication} - {self.date_created}"

templates/about.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
<style>
  /* CSS code goes here */
  .table th {
    background-color: #eee;
    font-weight: bold;
  }
  
  
  .table td {
    border: 1px solid #ccc;
    padding: 5px;
  }
  
  /* increase the font size of the footer */
  footer {
    font-size: 1.2em;
  }
</style>
<div style="background-color: #25d366;
            color: #fff;
            position: fixed;
            bottom: 20px;
            left: 20px;
            padding: 10px ;
            border-radius: 30px;
            box-shadow: 0px 3px 3px #ccc;
            z-index: 9999;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.3);
            opacity: 0.8;">
           
  <a href="https://wa.me/7994667412" target="_blank" rel="noopener" style="color: #fff;
                                                                          text-decoration: none;">
    <img src="https://imgs.search.brave.com/mkt9M6OBNiZn2BQOW4IQtvI31KMqZB6XaL9Eb13bCIs/rs:fit:1200:1200:1/g:ce/aHR0cDovL3BsdXNw/bmcuY29tL2ltZy1w/bmcvd2hhdHNhcHAt/cG5nLXdhemFwcC1s/b2dvLXdoYXRzLXdo/YXRzYXBwLWxvZ28t/d2hhdHNhcHAtaWNv/bi0yMDUwLnBuZw" alt="WhatsApp Logo" style="height: 50px;
                                                             margin-right: 0px;">
    
  </a>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>About Our Hospital</h1>
      <p>We are a leading provider of healthcare services in our community, offering a wide range of medical specialties and cutting-edge treatments to help our patients achieve their best possible health outcomes.</p>
      <p>At our hospital, we are committed to providing the highest level of care to our patients, with a focus on clinical excellence, patient safety, and personalized attention. Our team of doctors, nurses, and support staff work together to ensure that every patient receives the care they need, when they need it.</p>
    </div>
    <div class="col-md-6">
<div style="display: flex; justify-content: center;">
  <img src="/static/images/aboutpage.jpg" alt="About us" style="width: 400px; height: 300px;">
</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2>Our History</h2>
      <p>Our hospital was founded in 1950 by Dr. John Bhaskaran, who saw the need for a dedicated healthcare facility in our community. Over the years, we have grown and expanded our services to meet the changing needs of our patients, while always staying true to our mission of providing high-quality, compassionate care.</p>
    </div>
    <div class="col-md-6">
      <h2>Our Achievements</h2>
      <ul>
        <li>Recipient of the 2020 Healthgrades Patient Safety Excellence Award</li>
        <li>Named one of the Top Hospitals in the State by KERALA Medical Board </li>
        <li>Designated as a Comprehensive Stroke Center by the Joint Commission</li>
        <li>Received the 2021 Best Co-operative hospital Award</li>
      </ul>
    </div>
  </div>

  <div class="container" style="align: center;">
  <h2>Test Packages and Prices</h2>
  <table class="table" align="center">
    <thead>
      <tr>
        <th>Test Package</th>
        <th>Price</th>
        <th>Tests Included</th>
        <th>Diagnosis</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Basic Combo</td>
        <td>₹100</td>
        <td>Blood Test, Urine Test</td>
        <td>General Health Checkup</td>
      </tr>
      <tr>
        <td>Advanced Combo</td>
        <td>₹200</td>
        <td>Blood Test, Urine Test, X-Ray</td>
        <td>Complete Health Checkup</td>
        </tr>
  <tr>
    <td>Cardiac Combo</td>
    <td>₹300</td>
    <td>Blood Test, ECG, Stress Test</td>
    <td>Cardiovascular Screening</td>
  </tr>
  <tr>
    <td>Diabetes Package</td>
    <td>₹150</td>
    <td>Blood Test, Urine Test, Glucose Test</td>
    <td>Diabetes Screening</td>
  </tr>
</tbody>
  </table>
  
  </div>
  <div class="container">
  <h2>Departments by Floor</h2>
  <table align="center" class="table">
    <thead>
      <tr>
        <th>Floor</th>
        <th>Department</th>
        <th>Phone Number</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1st Floor</td>
        <td>Emergency Department</td>
        <td>1234567890</td>
      </tr>
      <tr>
        <td>1st Floor</td>
        <td>Pharmacy</td>
        <td>0987654321</td>
      </tr>
      <tr>
        <td>2nd Floor</td>
        <td>Cardiology</td>
        <td>1111122222</td>
      </tr>
      <tr>
        <td>2nd Floor</td>
        <td>Neurology</td>
        <td>2222233333</td>
      </tr>
      <tr>
        <td>3rd Floor</td>
        <td>Oncology</td>
        <td>3333344444</td>
      </tr>
      <tr>
        <td>3rd Floor</td>
        <td>Pulmonology</td>
        <td>4444455555</td>
      </tr>
    </tbody>
  </table>
</div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  

  <!-- Custom CSS -->
  
</head>
<body>
  <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="container">
    

		<a class="navbar-brand" href="{% url 'index' %}">
			<img src="{% static 'images/logo2.png' %}" alt="Co-operative Hospital" class="logo">
			<span class="hospital-name">Co-operative Hospital</span>
		  </a>
		  
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="background-color:white;" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
    


        <ul class="navbar-nav mr-auto">
           <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="doctorDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Patient?
            </a>
            <div class="dropdown-menu" aria-labelledby="doctorDropdown">
              <a class="dropdown-item" href="{% url 'booking' %}">Book Now</a>
              <a class="dropdown-item" href="{%url 'patient_login'%}">Patient Login</a>
              <a class="dropdown-item" href="{%url 'patient_register'%}">Don't have an account Register?</a>
              <a class="dropdown-item" href="{%url 'patient_index'%}">See your Prscriptions and appoinments</a>
              <a class="dropdown-item" href="{%url 'patient_logout'%}">Logout</a>
              
            </div>
          </li>
        </ul>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'booking' %}">Book Now</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Department' %}">Departments</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Doctor' %}">Doctors</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="doctorDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Doctor?
            </a>
            <div class="dropdown-menu" aria-labelledby="doctorDropdown">
              <a class="dropdown-item" href="{%url 'login'%}">Login</a>
              <a class="dropdown-item" href="{%url 'doctor_dashboard'%}">Doctor Dashboard</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
        </ul>

      </div>
    </div>
  </nav>
  

  <!-- Page content -->
  <div class="container py-4">
    
    {% block content %}
    {% endblock %}
  </div>

  <footer class="footer">
	<div class="container">
	  <div class="row">
		<div class="col-md-4">
		  <h3>Navigation</h3>
		  <ul class="list-unstyled">
			<li><a href="{% url 'index' %}">Home</a></li>
			<li><a href="{% url 'about' %}">About</a></li>
			<li><a href="{% url 'contact' %}">Contact</a></li>
			<li><a href="{% url 'booking' %}">Book Now</a></li>
			<li><a href="{% url 'Department' %}">Departments</a></li>
			<li><a href="{% url 'Doctor' %}">Doctors</a></li>
		  </ul>
		</div>
		<div class="col-md-4">
		  <h3>Connect With Us</h3>
		  <ul class="list-unstyled">
			<li><a href="#"><i class="fab fa-facebook"></i> Facebook</a></li>
			<li><a href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
			<li><a href="#"><i class="fab fa-instagram"></i> Instagram</a></li>
			<li><a href="#"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
		  </ul>
		</div>
		<div class="col-md-4">
		  <h3>Contact Us</h3>
		  <p><i class="fas fa-map-marker-alt"></i> co- oparative hospital mullakkal,alappuzha,kerala INDIA</p>
		  <p><i class="fas fa-phone"></i>0477 235 335</p>
		  <p><i class="fas fa-envelope"></i> info@hospital.com</p>
		</div>
	  </div>
	</div>
  </footer>
  
			  <!-- jQuery and Bootstrap JS -->
			  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
			  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
			  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
			  <!-- Custom JS -->
			  
			</body>
			<style>

.navbar-toggler {
box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.75);
}
/* Add 3D effect */
.navbar {
  background-color: #fff;
  box-shadow: 0 8px 16px rgba(0,0,0,0.5);
  transition: 0.3s;
}

.navbar:hover {
  box-shadow: 0 16px 32px rgba(0,0,0,0.4);
}

/* Add animation effect */
.navbar-nav .nav-item {
  position: relative;
}

.navbar-nav .nav-item:hover:before {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 2px;
  background-color: #007bff;
  transform: scaleX(0);
  transition: transform 0.3s ease-out;
  transform-origin: bottom right;
}

.navbar-nav .nav-item:hover:after {
  content: '';
  position: absolute;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 2px;
  background-color: #007bff;
  transform: scaleX(0);
  transition: transform 0.3s ease-out;
  transform-origin: bottom left;
}

.navbar-nav .nav-item:hover:before,
.navbar-nav .nav-item:hover:after {
  transform: scaleX(1);
}

.dropdown-menu {
  animation: fadeInDown 0.5s;
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    transform: translate3d(0, -20px, 0);
  }
  100% {
    opacity: 1;
    transform: translate3d(0, 0, 0);
  }
}

				.footer {
					background-color: #f2f2f2;
					padding: 50px 0;
				  }
				  
				  .footer h3 {
					color: #333;
				  }
				  
				  .footer ul {
					list-style: none;
					padding: 0;
				  }
				  
				  .footer li {
					margin-bottom: 10px;
				  }
				  
				  .footer a {
					color: #333;
				  }
				  
				  .footer a:hover {
					color: #007bff;
				  }
				  
				  .footer i {
					margin-right: 10px;
				  }
				  
				  .footer p {
					margin-bottom: 10px;
				  }
				  
				  @media (max-width: 767px) {
					.footer {
					  text-align: center;
					}
					
					.footer ul {
					  margin-bottom: 20px;
					}
				  }
				  
				.logo {
					max-width: 40px;
					margin-right: 10px;
				  }
				  
				 .hospital-name {
  font-size: 22px;
  font-weight: bold;
  color: #f15a29;
  text-shadow: 2px 2px 5px rgba(0,0,0,0.3);
  transform: translateZ(30px);
  display: inline-block;
  padding: 10px 20px;
  border: 2px solid #f15a29;
  border-radius: 10px;
  box-shadow: 2px 2px 5px rgba(0,0,0,0.3);
}
				

		    </style>
			</html>
			
			
			

templates/booking.html
{% extends 'base.html' %}
{% block title %}Booking for patients{% endblock %}
{% block content %}

  <div class="floating-btn">
    <a href="https://wa.me/7994667412" target="_blank" rel="noopener" style="color: #fff; text-decoration: none;">
      <img src="https://imgs.search.brave.com/mkt9M6OBNiZn2BQOW4IQtvI31KMqZB6XaL9Eb13bCIs/rs:fit:1200:1200:1/g:ce/aHR0cDovL3BsdXNw/bmcuY29tL2ltZy1w/bmcvd2hhdHNhcHAt/cG5nLXdhemFwcC1s/b2dvLXdoYXRzLXdo/YXRzYXBwLWxvZ28t/d2hhdHNhcHAtaWNv/bi0yMDUwLnBuZw" alt="WhatsApp Logo" style="height: 50px; margin-right: 0px;">
    </a>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow">
          <div class="card-body">
            <center>
              <h1>Book your Appointment</h1>
            </center>
            {% if messages %}
              <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">
                {% for message in messages %}
                  {{ message }}<br>
                {% endfor %}
              </div>
            {% endif %}
            <small><strong>if the username you used to ligin/register is not equal to booking name then you should ask your doctor for your digital prescription</strong></small> 
            <form method="post" class="appointment-form">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {{ field.label_tag }}
                  {{ field }}
                  {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
                  {% for error in field.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                  {% endfor %}
                </div>
              {% endfor %}
              <button type="submit" class="btn-submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>

  


            <center>
 <p style="background-color: #f2f2f2; color: #333333;">For more information, please visit:</p>
   <hr>
   <div style="background-color: #f2f2f2; padding: 10px;">

  <ul style="list-style: none; padding: 0;">
    <li style="margin-bottom: 5px;"><a href="{% url 'Doctor' %}" style="color: #0072c6;">Our Doctors</a></li>
     <hr>
    <li style="margin-bottom: 5px;"><a href="{% url 'Department' %}" style="color: #005bab;">Our Departments</a></li>
     <hr>
    <li style="margin-bottom: 5px;"><a href="{% url 'index' %}" style="color: #00437d;">Go to Home</a></li>
     <hr>
  </ul>
  </center>
</div>
</div>
</div>
</div>
</div>
<style>
/* Styles for floating WhatsApp button */
.floating-btn {
  position: fixed;
  bottom: 20px;
  right: 20px;
  z-index: 9999;
}

/* Styles for card shadow */
.card.shadow {
  box-shadow: 0px 0px 5px rgba(0,0,0,0.1);
}

/* Styles for form */
.appointment-form {
  margin-top: 20px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  font-weight: bold;
}

.form-group input[type="text"],
.form-group input[type="email"],
.form-group select {
  display: block;
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
  font-size: 16px;
}

.form-group select {
  height: 40px;
}

.form-text {
  margin-top: 5px;
  display: block;
}

.form-text.text-muted {
  color: #aaa;
}

.form-text.text-danger {
  color: #f00;
}

.btn-submit {
  display: block;
  margin-top: 20px;
  background-color: #4caf50;
  color: #fff;
  border: none;
  border-radius: 4px;
  padding: 10px 20px;
  font-size: 16px;
  cursor: pointer;
}

.btn-submit:hover {
  background-color: #3e8e41;
}

/* Styles for doctors and departments */
.col-sm-4 {
  margin-bottom: 20px;
}

.list-unstyled li {
  margin-bottom: 5px;
}

.list-unstyled li a {
  text-decoration: none;
  color: #000;
}

.list-unstyled li a:hover {
  text-decoration: underline;
}

</style>
{% endblock %}

templates/booking_success.html
{% extends 'base.html' %}

{% block title%}Your Booking was Successful {%endblock%}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow p-3 mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title text-center">Booking Successful!</h5>
            <p class="card-text text-center">Our team will contact you soon for confirmation.</p>
            <hr>
            <div class="booking-details">
             <center> <h4><u>Patient Details</u></h4></center>
              <ul>
                <li><strong>Name:</strong> {{ booking.patient_name }}</li>
                <li><strong>Patient Type:</strong> {{ booking.patient_type }}</li>
                <li><strong>Email:</strong> {{ booking.patient_email }}</li>
                <li><strong>Contact:</strong> {{ booking.patient_phone }}</li>
                <li><strong>Gender:</strong> {{ booking.get_patient_gender_display }}</li>
                <li><strong>Age:</strong> {{ booking.patient_age }}</li>
              </ul>
              <hr>
              <h4>Booked Doctor</h4>
              <p>Dr.{{ booking.doctor.doc_name }}</p>

<p><strong>NOTE:</strong> Take a screenshot of this page and show it at the reception to receive your physical Token</p>
<style>
  p strong {
  color: #FF5733;
}

p {
  display: inline-block;
  margin-right: 10px;
}

</style>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <style>
    .card {
      animation: fadein 1s;
    }
    .booking-details {
      margin-top: 20px;
      margin-bottom: 20px;
    }
    .booking-details h4 {
      font-size: 18px;
      margin-bottom: 10px;
    }
    .booking-details ul {
      list-style: none;
      padding-left: 0;
      margin-bottom: 10px;
    }
    .booking-details ul li {
      margin-bottom: 5px;
    }
  </style>

  <script>
    $(document).ready(function(){
      $(".card").hide().fadeIn(1000);
    });
  </script>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}contact us{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-md-6">
      <div style="background-color: #25d366;
            color: #fff;
            position: fixed;
            bottom: 20px;
            left: 20px;
            padding: 10px ;
            border-radius: 30px;
            box-shadow: 0px 3px 3px #ccc;
            z-index: 9999;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.3);
            opacity: 0.8;">
           
  <a href="https://wa.me/7994667412" target="_blank" rel="noopener" style="color: #fff;
                                                                          text-decoration: none;">
    <img src="https://imgs.search.brave.com/mkt9M6OBNiZn2BQOW4IQtvI31KMqZB6XaL9Eb13bCIs/rs:fit:1200:1200:1/g:ce/aHR0cDovL3BsdXNw/bmcuY29tL2ltZy1w/bmcvd2hhdHNhcHAt/cG5nLXdhemFwcC1s/b2dvLXdoYXRzLXdo/YXRzYXBwLWxvZ28t/d2hhdHNhcHAtaWNv/bi0yMDUwLnBuZw" alt="WhatsApp Logo" style="height: 50px;
                                                             margin-right: 0px;">
    
  </a>
</div>
      <h1>Contact Us</h1>
      {% if success_message %}
        <p class="success">{{ success_message }}</p>
      {% endif %}
      <form method="post" class="contact-form">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.name.id_for_label }}">Name</label>
          {{ form.name }}
        </div>
        <div class="form-group">
          <label for="{{ form.email.id_for_label }}">Email</label>
          {{ form.email }}
        </div>
        <div class="form-group">
          <label for="{{ form.subject.id_for_label }}">Subject</label>
          {{ form.subject }}
        </div>
        <div class="form-group">
          <label for="{{ form.message.id_for_label }}">Message</label>
          {{ form.message }}
        </div>
      <button type="submit" class="btn btn-lg btn-custom">Submit</button>

      </form>
    </div>
    <div class="col-md-6">
      <h2>Contact Information</h2>
      <ul>
        <li><i class="fa fa-phone"></i> Head Department : 1234554321</li>
        <li><i class="fa fa-phone"></i> Reception: 1234567899</li>
        <li><i class="fa fa-envelope"></i> Email: contact@co-operative_alpy.com</li>
        <li><i class="fa fa-map-marker"></i> Address: abcd road mullakkal alappuzha, Kerala, INDIA</li>
      </ul>
    </div>
  </div>

  <style>
    .contact-form {
      background-color: #f5f5f5;
      border-radius: 10px;
      padding: 20px;
    }

    .form-group {
      margin-bottom: 20px;
    }

    label {
      font-weight: bold;
      display: block;
      margin-bottom: 5px;
    }

    input[type=text], input[type=email], textarea {
      border-radius: 5px;
      border: none;
      padding: 10px;
      width: 100%;
    }
.btn-custom {
  background-color: #3498db;
  color: #fff;
  border-radius: 20px;
  padding: 10px 30px;
  font-size: 18px;
  text-align: center;
  display: block;
  margin: auto;
}

.btn-custom:hover {
  background-color: #2980b9;
}

    .success {
      color: green;
      font-weight: bold;
    }
    .btn-primary {
    background-color: #3498db;
    border-color: #3498db;
    color: #fff;
  }

  .btn-primary:hover {
    background-color: #2980b9;
    border-color: #2980b9;
  }

  .btn-primary:focus {
    box-shadow: none;
  }
  label {
  font-weight: bold;
  display: block;
  margin-bottom: 5px;
}

input[type="text"], input[type="email"], input[type="number"], select, textarea {
  width: 100%;
  padding: 10px;
  font-size: 16px;
  border-radius: 5px;
  border: 1px solid #ccc;
  margin-bottom: 20px;
}

input[type="text"]:focus, input[type="email"]:focus, input[type="number"]:focus, select:focus, textarea:focus {
  outline: none;
  border-color: #3e2af3;
  box-shadow: 0px 0px 8px rgba(243, 42, 42, 0.2);
}

.btn {
  text-decoration: none;
  color: #fff;
  border: none;
  cursor: pointer;
}

.btn-primary {
  background-color: #f32a2a;
  border-color: #ff6347;
}

.btn-primary:hover {
  background-color: #4749ff;
}





</style>
  </style>
{% endblock %}